# Header
menu:
  主页: /
  文章列表: /archives
  举个栗子: /project
  你说我说: /soso
  订了个阅: /atom.xml


# Content
excerpt_link: 阅读全文
prev: 上一页
next: 下一页
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- search
- author
#- music
- recent_posts
- category
- tag
#- tagcloud
#- news

# Miscellaneous
google_analytics:  #好像沒用了，代碼裏注釋掉了
changyanAppId: cyt6d5PUS
changyanConf: prod_ae46027aa49ac2fe7a466e24ef337d1f
rss: /atom.xml
google_site_verification: #好像沒用了，代碼裏注釋掉了
baidu_site_verification: 43om1SQhig
_360_site_verification: 09e51ecaa091dc6562d9b66976940fc8
favicon: /css/images/favicon.ico
music: true #使用网易云音乐
twitter: #代碼裏注釋掉了
google_plus: #代碼裏注釋掉了
fb_admins: #代碼裏注釋掉了
fb_app_id: #代碼裏注釋掉了

# Project
projects:
  project1:
    name: threejs元素周期表
    imagesrc: ./threejs/image/threejs.png
    projectaddress: ./threejs/index.html
  project2:
    name: 旋转的方块
    imagesrc: ./project1/image/project1.png
    projectaddress: ./project1/index.html
  project3:
    name: 抖动的线
    imagesrc: ./canvas1/image/canvas1.png
    projectaddress: ./canvas1/index.html
  project4:
    name: postMessage
    imagesrc: ./cross1/images/cross1.jpg
    projectaddress: ./cross1/index.html
  project5:
    name: 事件冒泡与捕获
    imagesrc: ./event1/images/event1.jpg
    projectaddress: ./event1/index.html